name = "testyourself-backend"
main = "src/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

[vars]
PROJECT_ID = "523c21d7-a822-4dbe-a30d-aa7e81936df3"
UPLOADS_BUCKET = "prod-523c21d7-a822-4dbe-a30d-aa7e81936df3"

# Secrets required:
# - STORAGE_API_TOKEN : Bearer token for storage.youware.me
# Configure via `wrangler secret put STORAGE_API_TOKEN`
