name: Deploy (Firebase Hosting + Functions)

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write     # Needed for Workload Identity Federation

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Authenticate to Google Cloud (no key)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: github-deployer@testyourself-80a10.iam.gserviceaccount.com

      - name: Install Firebase CLI and jq
        run: |
          npm install -g firebase-tools
          sudo apt-get update && sudo apt-get install -y jq

      - name: Install dependencies and build web app
        run: |
          npm ci
          npm run build

      - name: Detect changes
        id: changes
        run: |
          if git diff --name-only HEAD~1 | grep -E '^functions/' >/dev/null 2>&1; then
            echo "functions_changed=true" >> $GITHUB_OUTPUT
          else
            echo "functions_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Build Functions
        if: steps.changes.outputs.functions_changed == 'true'
        run: |
          cd functions
          npm ci
          npm run build

      - name: Deploy Hosting + Functions
        if: github.event_name == 'push' && steps.changes.outputs.functions_changed == 'true'
        run: |
          firebase deploy --only hosting,functions --project testyourself-80a10 --non-interactive

      - name: Deploy Hosting only
        if: github.event_name == 'push' && steps.changes.outputs.functions_changed != 'true'
        run: |
          firebase deploy --only hosting --project testyourself-80a10 --non-interactive

      - name: Deploy preview (PR)
        id: preview
        if: github.event_name == 'pull_request'
        run: |
          npx firebase-tools hosting:channel:deploy pr-${{ github.event.number }} \
            --project testyourself-80a10 --json > preview.json
          echo "url=$(jq -r '.result[]?.url // .result?.url' preview.json)" >> $GITHUB_OUTPUT

      - name: Comment preview URL
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            🚀 Firebase Preview: ${{ steps.preview.outputs.url }}

      - name: Deploy to Staging (staging branch)
        if: github.ref == 'refs/heads/staging' && github.event_name == 'push'
        run: |
          npx firebase-tools hosting:channel:deploy staging-$(date +%s) --project testyourself-80a10
