name: Deploy Firebase Hosting

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "public/**"
      - "package.json"
      - "vite.config.*"
      - "next.config.*"
      - "firebase.json"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Install deps
        run: npm ci

      - name: Build web
        run: npm run build

      # Requires FIREBASE_TOKEN secret (from `firebase login:ci`)
      - name: Deploy hosting
        run: firebase deploy --only hosting --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

