name: preview-cleanup
on:
  pull_request:
    types: [closed]
    branches: [ main ]

permissions:
  contents: read
  id-token: write

env:
  FIREBASE_SITE_ID: "testyourself-80a10"
  FIREBASE_PROJECT_ID: "testyourself-80a10"

jobs:
  delete-channel:
    runs-on: ubuntu-latest
    steps:
      - name: Auth to Google (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.DEPLOYER_SA }}

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Delete preview channel
        run: |
          CHANNEL="pr-${{ github.event.number }}"
          firebase hosting:channel:delete "" \
            --project "" \
            --site "" \
            --force || true
