name: Secret Scan (detect-secrets)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  scan:
    name: Run detect-secrets via pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pre-commit & detect-secrets
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit detect-secrets

      # Ensure a baseline exists so pre-commit hook runs consistently in CI.
      - name: Ensure baseline exists
        run: |
          if [ ! -f ".secrets.baseline" ]; then
            echo "::notice::No .secrets.baseline found; generating a new one for CI"
            detect-secrets scan --exclude-files "(node_modules|dist|build|android|ios|.git|.firebase|.venv|venv|.next|out)/" > .secrets.baseline
          fi

      - name: Run pre-commit (detect-secrets) on all files
        run: |
          pre-commit install --install-hooks
          # Run all hooks, which includes detect-secrets from .pre-commit-config.yaml
          pre-commit run --all-files
        # Always collect logs even if the hook fails
        continue-on-error: true

      - name: Save pre-commit log
        if: always()
        run: |
          mkdir -p artifacts
          # Dump last pre-commit run output if available
          echo "Pre-commit completed with status: $?" > artifacts/precommit-status.txt
          # Keep baseline for reference
          if [ -f ".secrets.baseline" ]; then cp .secrets.baseline artifacts/; fi

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detect-secrets-artifacts
          path: artifacts

      # If pre-commit failed earlier, mark the job as failed now to block merges
      - name: Fail if pre-commit found issues
        run: |
          # Re-run to get a proper non-zero exit when there are issues
          pre-commit run --all-files

